### ISSUE TITLE
bug: `buflisted` in `buf_options` not respected

### ISSUE THREAD

**Issue by mehalter** [stevearc/oil.nvim#220]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

NVIM v0.9.4

### Operating system/version

Arch Linux

### Describe the bug

By default `buflisted = false` is set in the `buf_options`. It looks like this is not always true. When navigating the directory structure up and down to parent/children directories I am getting strange behavior where the buffers all of a sudden start spawning with `buflisted = true`.

The pattern seems to be if I navigate into children directories the new buffers are `buflisted = false`, but the second I do `-` and navigate to a parent directory the buffer is set to `buflisted = false` as I would expect, but then navigating into children directories, they are all `buflisted = true`.

Also to note, this is replicated with the exact default `repro.lua` that was originally provided below, I have made no modifications to it.

### Steps To Reproduce

1. `nvim -u repro.lua`
2. Run `:Oil`
3. check `:lua =vim.bo.buflisted` and see it is `false`
4. go to parent with `-` and check, `:lua =vim.bo.buflisted` shows `false`
5. go back into the original directory (or any directory, but the original one will definitely exist
6. run `:lua =vim.bo.buflisted` and see that it is set to `true` and subsequent buffers when navigating are also `buflisted = true` from now on.

### Expected Behavior

`buf_options` should always be adhered to when navigating through the directory structure. It seems that the `bufhidden` option is setting correctly, but `buflisted` is getting messed up. I haven't done exhaustive testing with other arbitrary buffer options to see if this can be replicated for other options

### Directory structure

any_folder/repro.lua

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
            })
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
This was from #214. Should be fixed now!

**Comment by mehalter** [comment]
@stevearc thanks so much! This isn't entirely fixed though. Now I only get `buflisted = true` when I do `-` and go up a parent after going down into a child. Using the same default `repro.lua` above.

1. `nvim -u repro.lua`
2. Run `:Oil`
3. check `:lua =vim.bo.buflisted` and see it is `false`
4. go to parent with `-` and check, `:lua =vim.bo.buflisted` shows `false`
5. go back into the original directory (or any directory, but the original one will definitely exist), `:lua =vim.bo.buflisted` shows `false`
6. go to parent again with `-`
6. run `:lua =vim.bo.buflisted` and see that it is set to `true` and subsequent buffers when navigating up to the parent will also be `buflisted = true` from now on.

**Comment by mehalter** [comment]
I also found another case where just opening and closing Oil can make it go `buflisted`

1. Open a file, `nvim -u repro.lua`
2. Open Oil, `:Oil`
3. Close Oil, `<C-c>`
4. Open Oil, `:Oil`
5. check buflisted and see it is set to true, `:lua =vim.bo.buflisted`

**Comment by stevearc** [comment]
This led me down quite the rabbit hole, but it should be working as expected now

**Comment by mehalter** [comment]
Awesome! Some quick tests and it seems to be pretty solid! I'll report back if I encounter any more weirdness. Thanks for the fix!
